compatibility_date = "2022-01-01"

name = "narou"
type = "javascript"
workers_dev = false

kv_namespaces = [{ binding = "DB", id = "03ca8539982843789a9abb57fdae31c6" }]

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format = "service-worker"

[site]
bucket = "./public"
entry-point = "."

[miniflare]
host = "localhost"
port = 3000
kv_persist = true
