name = "narou-proxy-dev"
type = "javascript"
account_id = "b5844f07873a66bd807cbee5aaa57206"
workers_dev = true
vars = { ENVIRONMENT = "development" }
kv_namespaces = [
  { binding = "DB", id = "5ebcfc28aca84170885353341f110c87", preview_id = "8624a9e395cc4df7bea14c76b1030557" },
]

[env.production]
name = "narou-proxy"
workers_dev = false
route = "proxy.ymkz.app/*"
zone_id = "ef3d6757406f55d81f25714eeca18076"
vars = { ENVIRONMENT = "production" }
kv_namespaces = [{ binding = "DB", id = "5ebcfc28aca84170885353341f110c87" }]

[build]
upload.format = "modules"
upload.main = "./worker.mjs"
command = "npm run build"

[dev]
port = 3002
